server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: job-service
          uri: lb://job-service
          predicates:
            - Path=/job/**
        - id: project-service
          uri: lb://project-service
          predicates:
            - Path=/project/**
